"""
train_pipeline.py — Support Integrity Auditor (SIA)
Standalone training script:
  Stage 1 → Pseudo-label generation (rule + resolution + cluster + optional LLM fusion)
  Stage 2 → DistilBERT-LoRA + metadata classifier training
  Stage 3 → Saves model artifacts to --output-dir

Usage:
  # Uses pseudo_labeled_dataset.csv generated by the notebook (fastest):
  python train_pipeline.py --pseudo-data pseudo_labeled_dataset.csv

  # Full pipeline from raw CSV (no LLM scoring):
  python train_pipeline.py --data customer_support_tickets.csv

  # Full pipeline with Mistral scores pre-generated by notebook:
  python train_pipeline.py --data customer_support_tickets.csv \\
                           --llm-scores mistral_scores.csv

  # Override training hyper-params:
  python train_pipeline.py --pseudo-data pseudo_labeled_dataset.csv \\
                           --epochs 10 --batch-size 32 --lr 2e-4
"""

import argparse
import os
import pickle
import json
import re
import sys
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer,
    AutoModel,
    get_linear_schedule_with_warmup,
)
from peft import get_peft_model, LoraConfig
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    recall_score,
    silhouette_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.utils.class_weight import compute_class_weight

# ──────────────────────────────────────────────────────────────
# Constants (must match notebook values exactly)
# ──────────────────────────────────────────────────────────────
DISTILBERT_MODEL = "distilbert-base-uncased"
MAX_LEN          = 128
BATCH_SIZE       = 32
EPOCHS_DEFAULT   = 10
LR_DEFAULT       = 2e-4
LORA_R           = 8
LORA_ALPHA       = 16
LORA_DROPOUT     = 0.1
DROPOUT          = 0.3
N_METADATA       = 3          # channel, category, res_time
N_CLASSES        = 2

PRIORITY_MAP = {"Low": 0, "Medium": 1, "High": 2, "Critical": 3}
INV_PRIORITY = {v: k for k, v in PRIORITY_MAP.items()}

CRITICAL_WORDS = [
    "outage", "security", "fraud", "breach", "data loss",
    "stolen card", "unauthorized", "cannot login", "system down",
    "payment failed", "account hacked", "service unavailable", "data corruption",
]
HIGH_WORDS = [
    "crash", "error", "failed", "sync", "invoice discrepancy",
    "login issue", "payment issue", "screen freezes", "api error",
    "application crash", "data not syncing",
]

# ──────────────────────────────────────────────────────────────
# Text helpers  (identical to notebook)
# ──────────────────────────────────────────────────────────────
def clean_ticket_text(text: str) -> str:
    if pd.isna(text):
        return ""
    text = str(text)
    text = re.sub(r"^Hi Support,\s*", "", text, flags=re.IGNORECASE)
    text = re.split(r"[?.!]", text)[0]
    return text.strip()


def clean_text(text: str) -> str:
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z0-9 ]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


# ──────────────────────────────────────────────────────────────
# Stage 1A – Rule-based NLP signal  (identical to notebook)
# ──────────────────────────────────────────────────────────────
def compute_rule_score(text: str):
    score = 0
    evidence = []
    for word in CRITICAL_WORDS:
        if word in text:
            score += 3
            evidence.append(word)
    for word in HIGH_WORDS:
        if word in text:
            score += 2
            evidence.append(word)

    if score >= 6:
        severity = 3
    elif score >= 4:
        severity = 2
    elif score >= 2:
        severity = 1
    else:
        severity = 0

    return severity, ",".join(evidence)


# ──────────────────────────────────────────────────────────────
# Stage 1B – Resolution-time regression signal  (notebook exact)
# ──────────────────────────────────────────────────────────────
def compute_resolution_score(df: pd.DataFrame) -> np.ndarray:
    rf = RandomForestRegressor(n_estimators=200, max_depth=5, random_state=42)
    rf.fit(df[["Resolution_Time_Hours"]], df["priority_num"])
    pred = rf.predict(df[["Resolution_Time_Hours"]])
    return pred.clip(0, 3).round().astype(int)


# ──────────────────────────────────────────────────────────────
# Stage 1C – Embedding + K-Means cluster signal  (notebook exact)
# ──────────────────────────────────────────────────────────────
def compute_cluster_score(df: pd.DataFrame, embeddings: np.ndarray) -> pd.Series:
    silhouette_scores: dict = {}
    for k in range(2, 9):
        kmeans_temp = KMeans(n_clusters=k, random_state=42, n_init=10)
        labels = kmeans_temp.fit_predict(embeddings)
        score = silhouette_score(
            embeddings, labels,
            sample_size=min(2000, len(df)), random_state=42,
        )
        silhouette_scores[k] = score
        print(f"  k={k} → {score:.4f}")

    best_k = max(silhouette_scores, key=silhouette_scores.get)
    print(f"  Best k = {best_k}")

    kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)
    df_copy = df.copy()
    df_copy["cluster"] = kmeans.fit_predict(embeddings)

    cluster_avg_resolution = (
        df_copy.groupby("cluster")["Resolution_Time_Hours"].mean().sort_values()
    )
    cluster_score_map = {
        cluster: rank
        for rank, cluster in enumerate(cluster_avg_resolution.index)
    }
    return df_copy["cluster"].map(cluster_score_map)


# ──────────────────────────────────────────────────────────────
# Stage 1D – Fusion  (notebook exact weights)
# ──────────────────────────────────────────────────────────────
def fuse_scores(df: pd.DataFrame) -> pd.Series:
    return (
        0.40 * df["llm_score"]
        + 0.30 * df["cluster_score"]
        + 0.20 * df["resolution_score"]
        + 0.10 * df["rule_score"]
    )


def inferred_severity_from_fusion(fusion: pd.Series) -> pd.Series:
    sev = pd.Series(0, index=fusion.index)
    sev.loc[fusion >= 0.75] = 1
    sev.loc[fusion >= 1.50] = 2
    sev.loc[fusion >= 2.25] = 3
    return sev


# ──────────────────────────────────────────────────────────────
# Pseudo-label generation pipeline
# ──────────────────────────────────────────────────────────────
def build_pseudo_labels(df_raw: pd.DataFrame, llm_scores_path: str | None) -> pd.DataFrame:
    print("\n[Stage 1] Pseudo-label generation …")
    required_cols = [
        "Ticket_ID", "Ticket_Subject", "Ticket_Description",
        "Priority_Level", "Ticket_Channel", "Issue_Category",
        "Resolution_Time_Hours", "Customer_Email",
    ]
    df = df_raw[required_cols].copy()

    # Text preprocessing
    df["clean_description"] = df["Ticket_Description"].apply(clean_ticket_text)
    df["clean_text"] = (
        df["Ticket_Subject"].fillna("") + " " + df["clean_description"].fillna("")
    )
    df["clean_text"] = df["clean_text"].apply(clean_text)

    # Priority numeric
    df["priority_num"] = df["Priority_Level"].map(PRIORITY_MAP)

    # 1A — Rule score
    print("  Computing rule-based NLP scores …")
    df[["rule_score", "rule_evidence"]] = df["clean_text"].apply(
        lambda x: pd.Series(compute_rule_score(x))
    )

    # 1B — Resolution score
    print("  Computing resolution-time regression scores …")
    df["resolution_score"] = compute_resolution_score(df)

    # 1C — Embedding + cluster score
    print("  Computing sentence embeddings (all-MiniLM-L6-v2) …")
    try:
        from sentence_transformers import SentenceTransformer
        emb_model = SentenceTransformer("all-MiniLM-L6-v2")
        embeddings = emb_model.encode(
            df["clean_text"].tolist(),
            batch_size=64,
            show_progress_bar=True,
            convert_to_numpy=True,
        )
        print("  Running K-Means silhouette search …")
        df["cluster_score"] = compute_cluster_score(df, embeddings)
    except ImportError:
        print("  [WARN] sentence-transformers not installed — cluster_score set to 0")
        df["cluster_score"] = 0

    # 1D — LLM score (load from file if available)
    if llm_scores_path and os.path.exists(llm_scores_path):
        print(f"  Loading LLM scores from {llm_scores_path} …")
        llm = pd.read_csv(llm_scores_path)
        df = df.merge(llm[["Ticket_ID", "llm_score"]], on="Ticket_ID", how="left")
        missing = df["llm_score"].isna().sum()
        if missing > 0:
            print(f"  [WARN] {missing} tickets missing LLM scores — filling with rule_score")
            df["llm_score"] = df["llm_score"].fillna(df["rule_score"])
    else:
        print(
            "  [INFO] mistral_scores.csv not found — using rule_score as llm_score proxy.\n"
            "         Run the notebook's LLM section to generate mistral_scores.csv for full accuracy."
        )
        df["llm_score"] = df["rule_score"]

    # Fusion + mismatch labels
    df["severity_fusion"] = fuse_scores(df)
    df["inferred_severity"] = inferred_severity_from_fusion(df["severity_fusion"])
    df["assigned_priority_num"] = df["Priority_Level"].map(PRIORITY_MAP)
    df["severity_delta"] = df["inferred_severity"] - df["assigned_priority_num"]
    df["mismatch"] = (abs(df["severity_delta"]) >= 2).astype(int)

    df["mismatch_type"] = "Consistent"
    df.loc[df["severity_delta"] >= 2, "mismatch_type"] = "Hidden Crisis"
    df.loc[df["severity_delta"] <= -2, "mismatch_type"] = "False Alarm"

    print(f"\n  Mismatch distribution:\n{df['mismatch'].value_counts()}")
    print(f"\n  Mismatch type distribution:\n{df['mismatch_type'].value_counts()}")
    return df


# ──────────────────────────────────────────────────────────────
# Dataset  (identical to notebook)
# ──────────────────────────────────────────────────────────────
class TicketDataset(Dataset):
    def __init__(self, df: pd.DataFrame, tokenizer, max_len: int):
        self.texts      = df["clean_text"].tolist()
        self.labels     = df["mismatch"].tolist()
        self.channels   = df["channel_encoded"].tolist()
        self.categories = df["category_encoded"].tolist()
        self.res_times  = df["resolution_score"].tolist()
        self.tokenizer  = tokenizer
        self.max_len    = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        return {
            "input_ids":      enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "channel":        torch.tensor(self.channels[idx],   dtype=torch.float),
            "category":       torch.tensor(self.categories[idx], dtype=torch.float),
            "res_time":       torch.tensor(self.res_times[idx],  dtype=torch.float),
            "label":          torch.tensor(self.labels[idx],     dtype=torch.long),
        }


# ──────────────────────────────────────────────────────────────
# Model  (identical to notebook)
# ──────────────────────────────────────────────────────────────
class DistilBERTLoRAWithMetadata(nn.Module):
    def __init__(
        self,
        model_name: str,
        lora_config: LoraConfig,
        n_metadata: int = N_METADATA,
        n_classes: int  = N_CLASSES,
        dropout: float  = DROPOUT,
    ):
        super().__init__()
        base_model  = AutoModel.from_pretrained(model_name)
        self.encoder = get_peft_model(base_model, lora_config)
        hidden_size  = base_model.config.hidden_size

        self.meta_proj = nn.Sequential(
            nn.Linear(n_metadata, 32),
            nn.ReLU(),
            nn.Dropout(dropout),
        )
        self.classifier = nn.Sequential(
            nn.Linear(hidden_size + 32, 256),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(256, n_classes),
        )

    def forward(self, input_ids, attention_mask, channel, category, res_time):
        outputs    = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = outputs.last_hidden_state[:, 0, :]
        meta       = torch.stack([channel, category, res_time], dim=1)
        meta_out   = self.meta_proj(meta)
        combined   = torch.cat([cls_output, meta_out], dim=1)
        return self.classifier(combined)


# ──────────────────────────────────────────────────────────────
# Train / eval epoch  (identical to notebook)
# ──────────────────────────────────────────────────────────────
def train_epoch(model, loader, optimizer, scheduler, criterion, device):
    model.train()
    total_loss, all_preds, all_labels = 0.0, [], []

    for batch in loader:
        input_ids      = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        channel        = batch["channel"].to(device)
        category       = batch["category"].to(device)
        res_time       = batch["res_time"].to(device)
        labels         = batch["label"].to(device)

        optimizer.zero_grad()
        logits = model(input_ids, attention_mask, channel, category, res_time)
        loss   = criterion(logits, labels)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()
        all_preds.extend(torch.argmax(logits, dim=1).cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    return (
        total_loss / len(loader),
        accuracy_score(all_labels, all_preds),
        f1_score(all_labels, all_preds, average="macro"),
    )


def eval_epoch(model, loader, criterion, device):
    model.eval()
    total_loss, all_preds, all_labels = 0.0, [], []

    with torch.no_grad():
        for batch in loader:
            input_ids      = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            channel        = batch["channel"].to(device)
            category       = batch["category"].to(device)
            res_time       = batch["res_time"].to(device)
            labels         = batch["label"].to(device)

            logits = model(input_ids, attention_mask, channel, category, res_time)
            loss   = criterion(logits, labels)

            total_loss += loss.item()
            all_preds.extend(torch.argmax(logits, dim=1).cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    return (
        total_loss / len(loader),
        accuracy_score(all_labels, all_preds),
        f1_score(all_labels, all_preds, average="macro"),
        all_preds,
        all_labels,
    )


# ──────────────────────────────────────────────────────────────
# Preprocessing helpers
# ──────────────────────────────────────────────────────────────
def preprocess_splits(train_df, val_df, test_df):
    """Fit scalers/encoders on train, transform all splits. Returns (train, val, test, artifacts)."""
    scaler = MinMaxScaler()
    train_df["resolution_time_norm"] = scaler.fit_transform(train_df[["Resolution_Time_Hours"]])
    val_df["resolution_time_norm"]   = scaler.transform(val_df[["Resolution_Time_Hours"]])
    test_df["resolution_time_norm"]  = scaler.transform(test_df[["Resolution_Time_Hours"]])

    le_channel = LabelEncoder()
    train_df["channel_encoded"] = le_channel.fit_transform(train_df["Ticket_Channel"].astype(str))
    val_df["channel_encoded"]   = le_channel.transform(val_df["Ticket_Channel"].astype(str))
    test_df["channel_encoded"]  = le_channel.transform(test_df["Ticket_Channel"].astype(str))

    le_category = LabelEncoder()
    train_df["category_encoded"] = le_category.fit_transform(train_df["Issue_Category"].astype(str))
    val_df["category_encoded"]   = le_category.transform(val_df["Issue_Category"].astype(str))
    test_df["category_encoded"]  = le_category.transform(test_df["Issue_Category"].astype(str))

    artifacts = {
        "scaler":      scaler,
        "le_channel":  le_channel,
        "le_category": le_category,
    }
    return train_df, val_df, test_df, artifacts


# ──────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="SIA Training Pipeline")
    parser.add_argument("--data",         default="customer_support_tickets.csv",
                        help="Path to raw CSV (used when --pseudo-data is not supplied)")
    parser.add_argument("--pseudo-data",  default=None,
                        help="Path to pseudo_labeled_dataset.csv (generated by notebook). "
                             "If supplied, Stage 1 is skipped entirely.")
    parser.add_argument("--llm-scores",   default="mistral_scores.csv",
                        help="Path to mistral_scores.csv (optional; used during pseudo-label fusion)")
    parser.add_argument("--output-dir",   default="saved_model",
                        help="Directory to save model + preprocessing artifacts")
    parser.add_argument("--epochs",       type=int,   default=EPOCHS_DEFAULT)
    parser.add_argument("--batch-size",   type=int,   default=BATCH_SIZE)
    parser.add_argument("--lr",           type=float, default=LR_DEFAULT)
    parser.add_argument("--max-len",      type=int,   default=MAX_LEN)
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # ── Stage 1: Load / generate pseudo-labels ──────────────────
    if args.pseudo_data and os.path.exists(args.pseudo_data):
        print(f"\n[Stage 1] Loading pre-generated pseudo-labels from {args.pseudo_data}")
        df = pd.read_csv(args.pseudo_data)
        print(f"  Loaded {df.shape[0]} rows")

        # Ensure clean_text exists
        if "clean_text" not in df.columns:
            df["clean_description"] = df["Ticket_Description"].apply(clean_ticket_text)
            df["clean_text"] = (
                df["Ticket_Subject"].fillna("") + " " + df["clean_description"].fillna("")
            ).apply(clean_text)
    else:
        if not os.path.exists(args.data):
            sys.exit(f"ERROR: neither --pseudo-data nor --data ({args.data}) found.")
        print(f"\n[Stage 1] Building pseudo-labels from {args.data}")
        df_raw = pd.read_csv(args.data)
        df = build_pseudo_labels(df_raw, args.llm_scores)
        df.to_csv("pseudo_labeled_dataset.csv", index=False)
        print("  Saved pseudo_labeled_dataset.csv")

    # ── Feature engineering for classifier ──────────────────────
    df["text"] = (
        df["clean_text"]
        + " [CHANNEL] " + df["Ticket_Channel"].astype(str)
        + " [CATEGORY] " + df["Issue_Category"].astype(str)
    )

    # ── Train / val / test split  (70 / 15 / 15, same as notebook) ──
    print("\n[Stage 2] Splitting dataset …")
    train_df, temp_df = train_test_split(
        df, test_size=0.30, stratify=df["mismatch"], random_state=42
    )
    val_df, test_df = train_test_split(
        temp_df, test_size=0.50, stratify=temp_df["mismatch"], random_state=42
    )
    print(f"  Train={len(train_df)}  Val={len(val_df)}  Test={len(test_df)}")

    train_df, val_df, test_df, artifacts = preprocess_splits(
        train_df.copy(), val_df.copy(), test_df.copy()
    )

    # Save preprocessing artifacts
    with open(os.path.join(args.output_dir, "scaler.pkl"), "wb") as f:
        pickle.dump(artifacts["scaler"], f)
    with open(os.path.join(args.output_dir, "le_channel.pkl"), "wb") as f:
        pickle.dump(artifacts["le_channel"], f)
    with open(os.path.join(args.output_dir, "le_category.pkl"), "wb") as f:
        pickle.dump(artifacts["le_category"], f)
    print(f"  Preprocessing artifacts saved to {args.output_dir}/")

    # ── Class weights ─────────────────────────────────────────────
    weights = compute_class_weight(
        class_weight="balanced",
        classes=np.unique(train_df["mismatch"]),
        y=train_df["mismatch"],
    )
    class_weights = torch.tensor(weights, dtype=torch.float).to(device)
    print(f"  Class weights: {class_weights}")

    # ── Tokenizer ─────────────────────────────────────────────────
    print(f"\n  Loading tokenizer ({DISTILBERT_MODEL}) …")
    tokenizer = AutoTokenizer.from_pretrained(DISTILBERT_MODEL)

    train_dataset = TicketDataset(train_df, tokenizer, args.max_len)
    val_dataset   = TicketDataset(val_df,   tokenizer, args.max_len)
    test_dataset  = TicketDataset(test_df,  tokenizer, args.max_len)

    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True)
    val_loader   = DataLoader(val_dataset,   batch_size=args.batch_size, shuffle=False)
    test_loader  = DataLoader(test_dataset,  batch_size=args.batch_size, shuffle=False)

    # ── Model ─────────────────────────────────────────────────────
    print("\n  Initialising DistilBERT-LoRA model …")
    lora_config = LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        bias="none",
        target_modules=["q_lin", "v_lin"],
        inference_mode=False,
    )
    model_clf = DistilBERTLoRAWithMetadata(DISTILBERT_MODEL, lora_config).to(device)

    criterion  = nn.CrossEntropyLoss(weight=class_weights)
    optimizer  = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, model_clf.parameters()),
        lr=args.lr,
        weight_decay=0.01,
    )
    total_steps  = len(train_loader) * args.epochs
    warmup_steps = int(0.1 * total_steps)
    scheduler    = get_linear_schedule_with_warmup(
        optimizer, num_warmup_steps=warmup_steps, num_training_steps=total_steps
    )

    # ── Training loop ─────────────────────────────────────────────
    print(f"\n[Stage 2] Training for {args.epochs} epochs …")
    history, best_val_f1 = [], 0.0

    for epoch in range(1, args.epochs + 1):
        print(f"\n{'='*55}")
        print(f"EPOCH {epoch}/{args.epochs}")
        print(f"{'='*55}")

        train_loss, train_acc, train_f1 = train_epoch(
            model_clf, train_loader, optimizer, scheduler, criterion, device
        )
        val_loss, val_acc, val_f1, _, _ = eval_epoch(
            model_clf, val_loader, criterion, device
        )
        print(f"Train → Loss: {train_loss:.4f} | Acc: {train_acc:.4f} | Macro F1: {train_f1:.4f}")
        print(f"Val   → Loss: {val_loss:.4f}   | Acc: {val_acc:.4f}   | Macro F1: {val_f1:.4f}")

        history.append({
            "epoch": epoch,
            "train_loss": train_loss, "train_acc": train_acc, "train_f1": train_f1,
            "val_loss": val_loss,     "val_acc": val_acc,     "val_f1": val_f1,
        })

        # Save best checkpoint
        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            torch.save(
                model_clf.state_dict(),
                os.path.join(args.output_dir, "best_model_state_dict.pt"),
            )
            print(f"  ✅ Best model saved (val F1={best_val_f1:.4f})")

    # ── Final evaluation ──────────────────────────────────────────
    print("\n=== FINAL TEST EVALUATION ===")
    # Load best checkpoint
    model_clf.load_state_dict(
        torch.load(os.path.join(args.output_dir, "best_model_state_dict.pt"),
                   map_location=device)
    )
    test_loss, test_acc, test_f1, test_preds, test_labels = eval_epoch(
        model_clf, test_loader, criterion, device
    )
    print(f"\nTest Loss: {test_loss:.4f}")
    print(f"Test Accuracy: {test_acc:.4f}")
    print(f"Test Macro F1: {test_f1:.4f}")
    print("\n=== CLASSIFICATION REPORT ===")
    print(classification_report(
        test_labels, test_preds,
        target_names=["Consistent (0)", "Mismatch (1)"],
        digits=4,
    ))

    recalls = recall_score(test_labels, test_preds, average=None)
    print("\n=== VERIFICATION THRESHOLD CHECK ===")
    print(f"Accuracy ≥ 0.83 : {'✅' if test_acc  >= 0.83 else '❌'} ({test_acc:.4f})")
    print(f"Macro F1 ≥ 0.82 : {'✅' if test_f1   >= 0.82 else '❌'} ({test_f1:.4f})")
    print(f"Recall class 0 ≥ 0.78: {'✅' if recalls[0] >= 0.78 else '❌'} ({recalls[0]:.4f})")
    print(f"Recall class 1 ≥ 0.78: {'✅' if recalls[1] >= 0.78 else '❌'} ({recalls[1]:.4f})")

    # ── Save config + history ─────────────────────────────────────
    config = {
        "model_name":     DISTILBERT_MODEL,
        "max_len":        args.max_len,
        "n_metadata":     N_METADATA,
        "n_classes":      N_CLASSES,
        "dropout":        DROPOUT,
        "lora_r":         LORA_R,
        "lora_alpha":     LORA_ALPHA,
        "lora_dropout":   LORA_DROPOUT,
        "channel_classes":   artifacts["le_channel"].classes_.tolist(),
        "category_classes":  artifacts["le_category"].classes_.tolist(),
        "test_accuracy":  float(test_acc),
        "test_macro_f1":  float(test_f1),
        "test_recall_0":  float(recalls[0]),
        "test_recall_1":  float(recalls[1]),
    }
    with open(os.path.join(args.output_dir, "training_config.json"), "w") as f:
        json.dump(config, f, indent=4)

    pd.DataFrame(history).to_csv(
        os.path.join(args.output_dir, "training_history.csv"), index=False
    )
    print(f"\n✅ All artifacts saved to {args.output_dir}/")


if __name__ == "__main__":
    main()
